default: &default
  adapter: postgresql
  encoding: unicode
  pool: 30
  port: 5432

development:
  <<: *default
  database: influence_evaluator_dev

test:
  <<: *default
  database: influence_evaluator_test

production:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
